apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: sk-furniture
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: sk-furniture
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: { app: mongo }
  template:
    metadata:
      labels: { app: mongo }
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits: { cpu: "500m", memory: "1Gi" }
          readinessProbe:
            tcpSocket: { port: 27017 }
            initialDelaySeconds: 5
          livenessProbe:
            tcpSocket: { port: 27017 }
            initialDelaySeconds: 15
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: sk-furniture
spec:
  selector: { app: mongo }
  ports:
    - port: 27017
      targetPort: 27017
